defaults:
  - _self_
  - task: hopper-medium-replay-v2

pipeline_name: mppo
mode: train
seed: 42
device: cuda:0

# Environment
discount: 0.99
normalize_reward: True

# Diffuser
solver: ddpm
diffusion_steps: 5
sampling_steps: 5
predict_noise: True
ema_rate: 0.995
actor_learning_rate: 0.0003

# Training
batch_size: 256
log_interval: 1000
save_interval: 100000
ema_update_interval: 5

# Inference
ckpt: latest
num_envs: 50
num_episodes: 3
num_candidates: 50
temperature: 0.5
use_ema: True

# Critic
critic_hidden_dim: 256
critic_learning_rate: 0.0003
gradient_steps: 1000000


# hydra
hydra:
  job:
    chdir: false

